print("enter only 4 digits also print >64 and <123")
a=int(input("enter the first digit"))
b=int(input())
c=int(input())
d=int(input())
print(chr(a))
print(chr(b))
print(chr(c))
print(chr(d))
